# Generated by Django 5.0.13 on 2025-03-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='customer',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Empresa'),
        ),
    ]
